/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class src_sig_sig */

#ifndef _Included_src_sig_sig
#define _Included_src_sig_sig
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     src_sig_sig
 * Method:    importPkey
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_tfsc_wallet_sdk_Wallet4Android_importPkey
  (JNIEnv *, jobject, jstring);

/*
 * Class:     src_sig_sig
 * Method:    newPkey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tfsc_wallet_sdk_Wallet4Android_newPkey
  (JNIEnv *, jobject);

/*
 * Class:     src_sig_sig
 * Method:    sigmessage
 * Signature: (JLjava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tfsc_wallet_sdk_Wallet4Android_sigmessage
  (JNIEnv *, jobject, jlong, jstring);

/*
 * Class:     src_sig_sig
 * Method:    vefmessage
 * Signature: (JLjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_tfsc_wallet_sdk_Wallet4Android_vefmessage
  (JNIEnv *, jobject, jlong, jstring, jstring);


JNIEXPORT jstring JNICALL Java_tfsc_wallet_sdk_Wallet4Android_sigTx
  (JNIEnv *, jobject, jlong, jstring);

JNIEXPORT jstring JNICALL Java_tfsc_wallet_sdk_Wallet4Android_signContractMessageTx
        (JNIEnv *, jobject, jlong, jstring);

JNIEXPORT jstring JNICALL Java_tfsc_wallet_sdk_Wallet4Android_GetBase58
  (JNIEnv *, jobject, jlong);


JNIEXPORT jstring JNICALL Java_tfsc_wallet_sdk_Wallet4Android_GetPubStr
  (JNIEnv *, jobject, jlong);



/*
 * Class:     src_sig_sig
 * Method:    ExportPriHexStr
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tfsc_wallet_sdk_Wallet4Android_ExportPriHexStr
  (JNIEnv *, jobject, jlong);

/*
 * Class:     src_sig_sig
 * Method:    ImportPriHexStr
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_tfsc_wallet_sdk_Wallet4Android_ImportPriHexStr
  (JNIEnv *, jobject, jstring);

/*
 * Class:     src_sig_sig
 * Method:    ExportMnemoic
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tfsc_wallet_sdk_Wallet4Android_ExportMnemoic
  (JNIEnv *, jobject, jlong);

/*
 * Class:     src_sig_sig
 * Method:    ImportMnemoic
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_tfsc_wallet_sdk_Wallet4Android_ImportMnemoic
  (JNIEnv *, jobject, jstring);


JNIEXPORT jstring JNICALL Java_tfsc_wallet_sdk_Wallet4Android_getPubStringBase64
  (JNIEnv *, jobject, jlong);

  /*
 * Class:     src_sig_sig
 * Method:    Base64Encode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tfsc_wallet_sdk_Wallet4Android_Base64Encode
  (JNIEnv *, jobject, jstring);

/*
 * Class:     src_sig_sig
 * Method:    Base64Decode
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tfsc_wallet_sdk_Wallet4Android_Base64Decode
  (JNIEnv *, jobject, jstring);


JNIEXPORT jstring JNICALL Java_tfsc_wallet_sdk_Wallet4Android_GetContractPubStr
        (JNIEnv *, jobject, jlong);



//JNIEXPORT jstring JNICALL Java_tfsc_wallet_sdk_Wallet4Android_signContractMessage
//        (JNIEnv *, jobject, jlong, jstring);

JNIEXPORT jstring JNICALL Java_tfsc_wallet_sdk_Wallet4Android_getEvmAddr
        (JNIEnv *env, jobject, jstring pub);


JNIEXPORT jstring JNICALL Java_tfsc_wallet_sdk_Wallet4Android_getBase58FromEvmAddr
        (JNIEnv *env, jobject, jstring evmaddr);

JNIEXPORT void JNICALL Java_tfsc_wallet_sdk_Wallet4Android_freePrikey
        (JNIEnv *, jobject, jlong);
#ifdef __cplusplus
}
#endif
#endif